// MSDF Font Loader
// Loads a pre-built MSDF atlas generated by @unionengine/font (ufont CLI).
// Atlas is a standard BMFont JSON + PNG pair.
//
// JSON format (ufont output):
//   { pages, chars: [[id,w,h,xoff,yoff,xadv,x,y], ...], size, width, height, line_height, kernings }

/**
 * Load a pre-built MSDF font atlas.
 *
 * @param {GPUDevice} device
 * @param {object}    opts
 * @param {string}    opts.json_url      URL to the BMFont JSON
 * @param {string}    opts.png_url       URL to the atlas PNG
 * @param {number}    [opts.display_size=20]  Desired font cap-height in CSS px
 * @returns {Promise<FontAtlas>}
 */
export async function load_msdf_font(device, { json_url, png_url, display_size = 20 }) {
    // ── 1. Fetch JSON metrics and PNG bitmap in parallel ─────────────────────
    const [metrics, bitmap] = await Promise.all([
        fetch(json_url).then(r => { if (!r.ok) throw new Error(`Font JSON load failed: ${r.status}`); return r.json(); }),
        fetch(png_url).then(r => { if (!r.ok) throw new Error(`Font PNG load failed: ${r.status}`); return r.blob(); })
              .then(b => createImageBitmap(b)),
    ]);

    const atlas_size  = metrics.size;          // render px used by ufont (e.g. 48)
    const line_height = metrics.line_height;   // px in atlas space (e.g. 63)
    const scale       = display_size / atlas_size;

    // Monospace advance (from space or first char with xadvance)
    const space_meta = metrics.chars.find(c => c[0] === 32);
    const xadvance   = space_meta ? space_meta[5] : metrics.chars[0][5];
    const glyph_w    = xadvance  * scale;
    const glyph_h    = line_height * scale;

    // ── 2. Build glyph map  ───────────────────────────────────────────────────
    // Each entry: { u0,v0,u1,v1, xoff,yoff, w,h } – all in screen-space px
    const glyph_map = new Map();
    for (const ch of metrics.chars) {
        const [id, cw, ch2, xoff, yoff, , x, y] = ch;
        glyph_map.set(id, {
            u0:   x / bitmap.width,
            v0:   y / bitmap.height,
            u1:   (x + cw)  / bitmap.width,
            v1:   (y + ch2) / bitmap.height,
            xoff: xoff * scale,
            yoff: yoff * scale,
            w:    cw   * scale,
            h:    ch2  * scale,
        });
    }

    const FALLBACK = glyph_map.get(63) ?? glyph_map.values().next().value; // '?'

    // ── 3. Upload atlas PNG as rgba8unorm GPU texture ─────────────────────────
    const texture = device.createTexture({
        label: 'msdf-atlas',
        size:  [bitmap.width, bitmap.height],
        format: 'rgba8unorm',
        usage:  GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT,
    });
    device.queue.copyExternalImageToTexture(
        { source: bitmap, flipY: false },
        { texture },
        [bitmap.width, bitmap.height],
    );

    const sampler = device.createSampler({
        label:     'msdf-sampler',
        magFilter: 'linear',
        minFilter: 'linear',
    });

    // ── 4. Return atlas interface ─────────────────────────────────────────────
    return {
        texture, sampler,
        glyph_w, glyph_h,
        atlas_w: bitmap.width,
        atlas_h: bitmap.height,
        atlas_size, scale,
        is_msdf: true,

        /**
         * Returns glyph draw info for a character.
         * @param {string} ch
         * @returns {{ u0,v0,u1,v1, xoff,yoff, w,h }}
         */
        get_glyph(ch) {
            const cp = ch.codePointAt(0) ?? 63;
            return glyph_map.get(cp) ?? FALLBACK;
        },
    };
}
