// MSDF Font Loader
// Loads a pre-built MSDF atlas generated by @unionengine/font (ufont CLI).
// Atlas is a standard BMFont JSON + PNG pair.
//
// JSON format (ufont output):
//   { pages, chars: [[id,w,h,xoff,yoff,xadv,x,y], ...], size, width, height, line_height, kernings }

/**
 * Load a pre-built MSDF font atlas.
 *
 * @param {GPUDevice} device
 * @param {object}    opts
 * @param {string}    opts.jsonUrl      URL to the BMFont JSON
 * @param {string}    opts.pngUrl       URL to the atlas PNG
 * @param {number}    [opts.displaySize=20]  Desired font cap-height in CSS px
 * @returns {Promise<FontAtlas>}
 */
export async function loadMsdfFont(device, { jsonUrl, pngUrl, displaySize = 20 }) {
    // ── 1. Fetch JSON metrics and PNG bitmap in parallel ─────────────────────
    const [metrics, bitmap] = await Promise.all([
        fetch(jsonUrl).then(r => { if (!r.ok) throw new Error(`Font JSON load failed: ${r.status}`); return r.json(); }),
        fetch(pngUrl).then(r => { if (!r.ok) throw new Error(`Font PNG load failed: ${r.status}`); return r.blob(); })
              .then(b => createImageBitmap(b)),
    ]);

    const atlasSize  = metrics.size;          // render px used by ufont (e.g. 48)
    const lineHeight = metrics.line_height;   // px in atlas space (e.g. 63)
    const scale      = displaySize / atlasSize;

    // Monospace advance (from space or first char with xadvance)
    const spaceMeta = metrics.chars.find(c => c[0] === 32);
    const xadvance  = spaceMeta ? spaceMeta[5] : metrics.chars[0][5];
    const glyphW    = xadvance  * scale;
    const glyphH    = lineHeight * scale;

    // ── 2. Build glyph map  ───────────────────────────────────────────────────
    // Each entry: { u0,v0,u1,v1, xoff,yoff, w,h } – all in screen-space px
    const glyphMap = new Map();
    for (const ch of metrics.chars) {
        const [id, cw, ch2, xoff, yoff, , x, y] = ch;
        glyphMap.set(id, {
            u0:   x / bitmap.width,
            v0:   y / bitmap.height,
            u1:   (x + cw)  / bitmap.width,
            v1:   (y + ch2) / bitmap.height,
            xoff: xoff * scale,
            yoff: yoff * scale,
            w:    cw   * scale,
            h:    ch2  * scale,
        });
    }

    const FALLBACK = glyphMap.get(63) ?? glyphMap.values().next().value; // '?'

    // ── 3. Upload atlas PNG as rgba8unorm GPU texture ─────────────────────────
    const texture = device.createTexture({
        label: 'msdf-atlas',
        size:  [bitmap.width, bitmap.height],
        format: 'rgba8unorm',
        usage:  GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT,
    });
    device.queue.copyExternalImageToTexture(
        { source: bitmap, flipY: false },
        { texture },
        [bitmap.width, bitmap.height],
    );

    const sampler = device.createSampler({
        label:     'msdf-sampler',
        magFilter: 'linear',
        minFilter: 'linear',
    });

    // ── 4. Return atlas interface ─────────────────────────────────────────────
    return {
        texture, sampler,
        glyphW, glyphH,
        atlasW: bitmap.width,
        atlasH: bitmap.height,
        atlasSize, scale,
        isMsdf: true,

        /**
         * Returns glyph draw info for a character.
         * @param {string} ch
         * @returns {{ u0,v0,u1,v1, xoff,yoff, w,h }}
         */
        getGlyph(ch) {
            const cp = ch.codePointAt(0) ?? 63;
            return glyphMap.get(cp) ?? FALLBACK;
        },
    };
}
