// MSDF Font Loader
// Loads a pre-built MSDF atlas generated by @unionengine/font (ufont CLI).
// Atlas is a standard BMFont JSON + PNG pair.

import type { GlyphInfo, FontAtlas } from './draw.ts';

interface BmFontJson {
    size:        number;
    line_height: number;
    width:       number;
    height:      number;
    chars:       [number, number, number, number, number, number, number, number][];
}

export interface LoadFontOptions {
    json_url:      string;
    png_url:       string;
    /** Desired font cap-height in CSS px (default 20). */
    display_size?: number;
}

/** Re-export FontAtlas so callers only need to import from font.ts */
export type { FontAtlas, GlyphInfo };

export async function load_msdf_font(device: GPUDevice, opts: LoadFontOptions): Promise<FontAtlas> {
    const { json_url, png_url, display_size = 20 } = opts;

    const [metrics, bitmap] = await Promise.all([
        fetch(json_url).then(r => {
            if (!r.ok) throw new Error(`Font JSON load failed: ${r.status}`);
            return r.json() as Promise<BmFontJson>;
        }),
        fetch(png_url)
            .then(r => { if (!r.ok) throw new Error(`Font PNG load failed: ${r.status}`); return r.blob(); })
            .then(b => createImageBitmap(b)),
    ]);

    const atlas_size  = metrics.size;
    const line_height = metrics.line_height;
    const scale       = display_size / atlas_size;

    const space_meta  = metrics.chars.find(c => c[0] === 32);
    const xadvance    = space_meta ? space_meta[5] : metrics.chars[0]![5];
    const glyph_w     = xadvance * scale;
    const glyph_h     = line_height * scale;

    const glyph_map = new Map<number, GlyphInfo>();
    for (const ch of metrics.chars) {
        const [id, cw, ch2, xoff, yoff, , x, y] = ch;
        glyph_map.set(id, {
            u0:   x / bitmap.width,
            v0:   y / bitmap.height,
            u1:   (x + cw)  / bitmap.width,
            v1:   (y + ch2) / bitmap.height,
            xoff: xoff * scale,
            yoff: yoff * scale,
            w:    cw   * scale,
            h:    ch2  * scale,
        });
    }

    const FALLBACK = glyph_map.get(63) ?? [...glyph_map.values()][0]!;

    const texture = device.createTexture({
        label:  'msdf-atlas',
        size:   [bitmap.width, bitmap.height],
        format: 'rgba8unorm',
        usage:  GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT,
    });
    device.queue.copyExternalImageToTexture(
        { source: bitmap },
        { texture },
        [bitmap.width, bitmap.height],
    );

    const sampler = device.createSampler({
        magFilter: 'linear',
        minFilter: 'linear',
    });

    return {
        glyph_w,
        glyph_h,
        atlasW: bitmap.width,
        atlasH: bitmap.height,
        texture,
        sampler,
        get_glyph(ch: string): GlyphInfo | undefined {
            return glyph_map.get(ch.charCodeAt(0)) ?? FALLBACK;
        },
    };
}
