/* Generated by tools/gen_embedded_ffi.py. Do not edit by hand. */
#include "ns_vm.h"
#include <string.h>

#if defined(NS_XCLIB)

typedef struct {
    i32 id;
} gpu_binding;
typedef struct {
    i32 id;
} gpu_mesh;
typedef struct {
    i32 id;
} gpu_pipeline;
typedef struct {
    i32 id;
} gpu_render_pass;
typedef struct {
    f64 r;
    f64 g;
    f64 b;
    f64 a;
} ui_color_rgba;
typedef struct {
    ns_bool hovered;
    ns_bool pressed;
} ui_hit;
typedef struct {
    f64 x;
    f64 y;
    f64 w;
    f64 h;
} ui_rect;
typedef struct {
    f64 w;
    f64 h;
} ui_text_size;

extern void * view_create(const char *, i32, i32);
extern void * view_create_no_title(const char *, i32, i32);
extern void view_run(void *);
extern void view_close(void *);
extern void view_capture_require(void *);
extern void view_on_scroll(void *, f64, f64);
extern void view_on_resize(void *, i32, i32);
extern void view_on_mouse_move(void *, f64, f64);
extern void view_on_mouse_btn(void *, i32, i32);
extern void view_on_key_action(void *, i32, i32);
extern ns_bool view_is_key_pressed(void *, i32);
extern i32 view_take_key_press(void *, i32);
extern void view_clear_key_presses(void *);
extern void view_on_pointer_event(void *, i32, i32, i32, f64, f64, f64, f64, f64, f64, i32);
extern void view_on_tool_action(void *, i32, f64);
extern void view_on_gesture(void *, f64, f64, f64, f64);
extern i32 view_input_count(void *);
extern void * view_input_at(void *, i32);
extern void * view_gesture(void *);
extern void view_input_reset(void *);
extern const char * view_get_clipboard(void *);
extern void view_set_clipboard(void *, const char *);
extern void * ui_input_empty(void);
extern void * ui_theme_empty(void);
extern void * ui_renderer_create(void *);
extern void ui_renderer_destroy(void *);
extern ns_bool ui_load_chinese_font(void *, const char *, const char *);
extern ns_bool ui_load_font(void *, const char *, const char *);
extern void ui_resize(void *);
extern void ui_resize_to(void *, i32, i32);
extern void ui_request_render(void *, i32);
extern void ui_begin_frame(void *);
extern void ui_flush(void *, ui_color_rgba *);
extern void ui_flush_overlay(void *, ui_color_rgba *);
extern i32 ui_canvas_width(void *);
extern i32 ui_canvas_height(void *);
extern void * ui_scene_create(void *);
extern void ui_scene_destroy(void *);
extern i32 ui_scene_mesh_create(void *);
extern ns_bool ui_scene_mesh_update(void *, i32, void *, i32, void *, i32);
extern void ui_scene_mesh_destroy(void *, i32);
extern void ui_scene_begin(void *, f64, f64, f64, f64, void *, u32);
extern void ui_scene_draw_grid(void *, f64, f64, f64);
extern void ui_scene_draw_mesh(void *, i32, void *, i32);
extern void ui_scene_draw_lines(void *, void *, i32, u32, f64);
extern void ui_scene_draw_points(void *, void *, i32, u32, f64);
extern void ui_scene_end(void *);
extern void * ui_gizmo(void *, i32, f64, f64, f64, f64, f64, ns_bool, ns_bool, ns_bool);
extern void * ui_gizmo_compact(void *, i32, void *);
extern i32 ui_atlas_load(void *, const char *);
extern void ui_atlas_destroy(void *, i32);
extern i32 ui_atlas_width(void *, i32);
extern i32 ui_atlas_height(void *, i32);
extern void ui_atlas_draw(void *, i32, f64, f64, f64, f64);
extern void ui_atlas_draw_region(void *, i32, f64, f64, f64, f64, f64, f64, f64, f64, u32);
extern void * ui_layout(f64, f64, f64, f64, f64, f64, i32);
extern void ui_fill_rect(void *, f64, f64, f64, f64, u32, f64);
extern void ui_fill_round_rect(void *, f64, f64, f64, f64, f64, u32, f64);
extern void ui_fill_round_rect_per_corner(void *, f64, f64, f64, f64, f64, f64, f64, f64, u32, f64);
extern void ui_stroke_round_rect(void *, f64, f64, f64, f64, f64, f64, u32, f64);
extern void ui_stroke_round_rect_per_corner(void *, f64, f64, f64, f64, f64, f64, f64, f64, f64, u32, f64);
extern void ui_stroke_rect(void *, f64, f64, f64, f64, f64, u32, f64);
extern void ui_fill_triangle(void *, f64, f64, f64, f64, f64, f64, u32, f64);
extern void ui_fill_circle(void *, f64, f64, f64, u32, f64);
extern void ui_stroke_circle(void *, f64, f64, f64, f64, u32, f64);
extern void ui_stroke_line(void *, f64, f64, f64, f64, f64, u32, f64);
extern void ui_stroke_polyline(void *, void *, i32, f64, u32, f64);
extern void ui_push_clip(void *, f64, f64, f64, f64);
extern void ui_push_clip_round(void *, f64, f64, f64, f64, f64);
extern void ui_pop_clip(void *);
extern ns_bool ui_rect_clipped(void *, f64, f64, f64, f64);
extern i32 ui_rect_batch_create(void *);
extern void ui_rect_batch_destroy(void *, i32);
extern void ui_rect_batch_begin(void *, i32);
extern void ui_rect_batch_add(void *, i32, f64, f64, f64, f64, u32);
extern ns_bool ui_rect_batch_end(void *, i32);
extern void ui_rect_batch_draw(void *, i32);
extern void ui_rect_batch_draw_at(void *, i32, f64, f64);
extern void ui_draw_text(void *, f64, f64, const char *, f64, u32, i32);
extern f64 ui_draw_text_wrapped(void *, f64, f64, f64, const char *, f64, u32, i32);
extern f64 ui_text_line_height(void *, f64, i32);
extern f64 ui_text_v_center_y(void *, f64, f64, f64, i32);
extern ui_text_size * ui_measure_text(void *, const char *, f64, i32);
extern f64 ui_text_width(void *, const char *, f64, i32);
extern f64 ui_mono_char_width(void *, f64, i32);
extern void * ui_widgets_create(void *);
extern void ui_widgets_destroy(void *);
extern void ui_widgets_set_light(void *, ns_bool);
extern void ui_widgets_begin_frame(void *, void *, void *);
extern void ui_widgets_begin_view(void *, void *, void *, ns_bool);
extern void ui_widgets_end_frame(void *);
extern ns_bool ui_button(void *, const char *, f64, f64, f64, f64, const char *, ns_bool);
extern f64 ui_slider(void *, const char *, f64, f64, f64, f64, f64, f64, f64, ns_bool);
extern f64 ui_slider_rect(void *, const char *, ui_rect *, f64, f64, f64);
extern f64 ui_slider_id(void *, i32, ui_rect *, f64, f64, f64);
extern ui_hit * ui_hit_region(void *, f64, f64, f64, f64);
extern ns_bool ui_is_escape_pressed(void *);
extern ns_bool ui_is_enter_pressed(void *);
extern ns_bool ui_is_mouse_down(void *);
extern ns_bool ui_is_mouse_pressed(void *);
extern ns_bool ui_has_keyboard_focus(void *);
extern f64 ui_widgets_mouse_x(void *);
extern f64 ui_widgets_mouse_y(void *);
extern ui_color_rgba * ui_color_picker(void *, const char *, f64, f64, f64, f64, ui_color_rgba *);
extern ui_color_rgba * ui_color_picker_rect(void *, const char *, ui_rect *, ui_color_rgba *);
extern ui_color_rgba * ui_color_picker_id(void *, i32, ui_rect *, ui_color_rgba *);
extern u32 ui_pack_color(const char *);
extern u32 ui_pack_rgba_floats(f64, f64, f64, f64);
extern void * os_lock_create(void);
extern ns_bool os_lock_acquire(void *);
extern ns_bool os_lock_try_acquire(void *);
extern ns_bool os_lock_release(void *);
extern void os_lock_destroy(void *);
extern void * os_semaphore_create(i32);
extern void * os_semaphore_create_bounded(i32, i32);
extern ns_bool os_semaphore_wait(void *);
extern ns_bool os_semaphore_try_wait(void *);
extern ns_bool os_semaphore_signal(void *);
extern void os_semaphore_destroy(void *);
extern f64 os_time(void);
extern u64 os_time_ms(void);
extern u64 os_time_us(void);
extern u64 os_time_ns(void);
extern void * os_date_now(void);
extern const char * os_time_string(void);
extern const char * os_date_string(void);
extern const char * os_locale_date_string(void);
extern const char * os_locale_date_time_string(void);
extern void os_vibrate(f64, f64);
extern i64 os_file_size(const char *);
extern const char * os_read_file(const char *);
extern const char * os_read_file_part(const char *, i64, i64);
extern i32 os_write_file_atomic(const char *, const char *);
extern const char * os_app_data_dir(const char *);
extern i32 os_dir_scan(const char *);
extern const char * os_entry_name(i32);
extern const char * os_entry_path(i32);
extern i32 os_entry_depth(i32);
extern i32 os_entry_parent(i32);
extern i32 os_entry_is_dir(i32);
extern i32 os_watch_start(const char *);
extern i32 os_watch_poll(void);
extern void os_watch_stop(void);
extern const char * os_open_file_dialog(const char *);
extern const char * os_save_file_dialog(const char *, const char *);
extern const char * os_open_folder_dialog(const char *);
extern const char * os_cwd(void);
extern const char * os_env(const char *);
extern i32 os_make_dirs(const char *);
extern i32 os_launch_ns_project(const char *, const char *);
extern ns_bool gpu_request_device(void *);
extern void gpu_destroy_device(void);
extern const char * gpu_shader_target(void);
extern ns_bool gpu_dispatch_compute_source(const char *, const char *, i32, i32, i32);
extern u32 gpu_create_buffer(i32, i32);
extern void gpu_update_buffer(u32, void *, i32);
extern u32 gpu_create_shader_source(const char *, const char *, const char *, const char *);
extern u32 gpu_create_pipeline_layout(u32, i32, void *, void *, void *, i32, i32, i32);
extern u32 gpu_create_mesh_1(u32, u32);
extern void gpu_destroy_buffer_id(u32);
extern void gpu_destroy_shader_id(u32);
extern void gpu_destroy_pipeline_id(u32);
extern void gpu_destroy_mesh_id(u32);
extern void gpu_begin_render_pass_id(u32);
extern void gpu_set_pipeline_id(u32);
extern void gpu_set_mesh_id(u32);
extern void gpu_begin_render_pass(gpu_render_pass);
extern void gpu_set_viewport(i32, i32, i32, i32);
extern void gpu_set_scissor(i32, i32, i32, i32);
extern void gpu_set_pipeline(gpu_pipeline);
extern void gpu_set_binding(gpu_binding);
extern void gpu_set_mesh(gpu_mesh);
extern void gpu_draw(i32, i32, i32);
extern void gpu_end_pass(void);
extern void gpu_commit(void);
extern void * io_load_image(const char *);
extern ns_bool io_save_image(const char *, void *);

static ns_value ns_embedded_arg(ns_vm *vm, i32 index) {
    ns_call *call = ns_array_last(vm->call_stack);
    return vm->symbol_stack[call->arg_offset + index].val;
}

static const char *ns_embedded_arg_str(ns_vm *vm, i32 index) {
    return ns_eval_str(vm, ns_embedded_arg(vm, index)).data;
}

static void *ns_embedded_arg_pointer(ns_vm *vm, i32 index) {
    ns_value value = ns_embedded_arg(vm, index);
    if (ns_type_is_array(value.t)) return ns_eval_array_raw(vm, value);
    if (ns_type_is_ref(value.t)) return ns_type_in_stack(value.t) ? (void *)&vm->stack[value.o] : (void *)value.o;
    return ns_type_in_stack(value.t) ? (void *)&vm->stack[value.o] : (void *)value.o;
}

static void ns_embedded_return_scalar(ns_vm *vm, const void *value, size_t size) {
    ns_call *call = ns_array_last(vm->call_stack);
    memcpy(&vm->stack[call->ret.o], value, size);
}

static void ns_embedded_return_pointer(ns_vm *vm, void *value) {
    ns_call *call = ns_array_last(vm->call_stack);
    call->ret.t = ns_type_set_stack(call->callee->fn.ret, false);
    call->ret.o = (u64)value;
}

static void ns_embedded_return_struct(ns_vm *vm, const void *value) {
    ns_call *call = ns_array_last(vm->call_stack);
    if (value) memcpy(&vm->stack[call->ret.o], value, (size_t)ns_type_size(vm, call->callee->fn.ret));
}

static void ns_embedded_return_array(ns_vm *vm, void *value) {
    ns_call *call = ns_array_last(vm->call_stack);
    *(u64 *)&vm->stack[call->ret.o] = (u64)value;
}

ns_return_bool ns_vm_call_embedded(ns_vm *vm) {
    ns_call *call = ns_array_last(vm->call_stack);
    ns_symbol *fn = call->callee;
    if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_create")) {
        void *result = view_create(ns_embedded_arg_str(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_create_no_title")) {
        void *result = view_create_no_title(ns_embedded_arg_str(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_run")) {
        view_run(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_close")) {
        view_close(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_capture_require")) {
        view_capture_require(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_scroll")) {
        view_on_scroll(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_resize")) {
        view_on_resize(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_mouse_move")) {
        view_on_mouse_move(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_mouse_btn")) {
        view_on_mouse_btn(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_key_action")) {
        view_on_key_action(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_is_key_pressed")) {
        ns_bool result = view_is_key_pressed(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_take_key_press")) {
        i32 result = view_take_key_press(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_clear_key_presses")) {
        view_clear_key_presses(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_pointer_event")) {
        view_on_pointer_event(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 9)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 10)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_tool_action")) {
        view_on_tool_action(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_on_gesture")) {
        view_on_gesture(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_input_count")) {
        i32 result = view_input_count(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_input_at")) {
        void *result = view_input_at(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_gesture")) {
        void *result = view_gesture(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_input_reset")) {
        view_input_reset(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_get_clipboard")) {
        const char *result = view_get_clipboard(ns_embedded_arg_pointer(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "view") && ns_str_equals_STR(fn->name, "view_set_clipboard")) {
        view_set_clipboard(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_input_empty")) {
        void *result = ui_input_empty();
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_theme_empty")) {
        void *result = ui_theme_empty();
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_renderer_create")) {
        void *result = ui_renderer_create(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_renderer_destroy")) {
        ui_renderer_destroy(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_load_chinese_font")) {
        ns_bool result = ui_load_chinese_font(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_embedded_arg_str(vm, 2));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_load_font")) {
        ns_bool result = ui_load_font(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_embedded_arg_str(vm, 2));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_resize")) {
        ui_resize(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_resize_to")) {
        ui_resize_to(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_request_render")) {
        ui_request_render(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_begin_frame")) {
        ui_begin_frame(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_flush")) {
        ui_flush(ns_embedded_arg_pointer(vm, 0), (ui_color_rgba *)ns_embedded_arg_pointer(vm, 1));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_flush_overlay")) {
        ui_flush_overlay(ns_embedded_arg_pointer(vm, 0), (ui_color_rgba *)ns_embedded_arg_pointer(vm, 1));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_canvas_width")) {
        i32 result = ui_canvas_width(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_canvas_height")) {
        i32 result = ui_canvas_height(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_create")) {
        void *result = ui_scene_create(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_destroy")) {
        ui_scene_destroy(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_mesh_create")) {
        i32 result = ui_scene_mesh_create(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_mesh_update")) {
        ns_bool result = ui_scene_mesh_update(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_embedded_arg_pointer(vm, 2), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)), ns_embedded_arg_pointer(vm, 4), ns_eval_number_i32(vm, ns_embedded_arg(vm, 5)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_mesh_destroy")) {
        ui_scene_mesh_destroy(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_begin")) {
        ui_scene_begin(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_embedded_arg_pointer(vm, 5), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_draw_grid")) {
        ui_scene_draw_grid(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_draw_mesh")) {
        ui_scene_draw_mesh(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_embedded_arg_pointer(vm, 2), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_draw_lines")) {
        ui_scene_draw_lines(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_pointer(vm, 1), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_draw_points")) {
        ui_scene_draw_points(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_pointer(vm, 1), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_scene_end")) {
        ui_scene_end(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_gizmo")) {
        void *result = ui_gizmo(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_bool(vm, ns_embedded_arg(vm, 7)), ns_eval_bool(vm, ns_embedded_arg(vm, 8)), ns_eval_bool(vm, ns_embedded_arg(vm, 9)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_gizmo_compact")) {
        void *result = ui_gizmo_compact(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_embedded_arg_pointer(vm, 2));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_load")) {
        i32 result = ui_atlas_load(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_destroy")) {
        ui_atlas_destroy(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_width")) {
        i32 result = ui_atlas_width(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_height")) {
        i32 result = ui_atlas_height(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_draw")) {
        ui_atlas_draw(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_atlas_draw_region")) {
        ui_atlas_draw_region(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 9)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 10)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_layout")) {
        void *result = ui_layout(ns_eval_number_f64(vm, ns_embedded_arg(vm, 0)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 6)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_fill_rect")) {
        ui_fill_rect(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_fill_round_rect")) {
        ui_fill_round_rect(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_fill_round_rect_per_corner")) {
        ui_fill_round_rect_per_corner(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 9)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 10)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_round_rect")) {
        ui_stroke_round_rect(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_round_rect_per_corner")) {
        ui_stroke_round_rect_per_corner(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 9)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 10)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 11)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_rect")) {
        ui_stroke_rect(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_fill_triangle")) {
        ui_fill_triangle(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_fill_circle")) {
        ui_fill_circle(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_circle")) {
        ui_stroke_circle(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_line")) {
        ui_stroke_line(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_stroke_polyline")) {
        ui_stroke_polyline(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_pointer(vm, 1), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_push_clip")) {
        ui_push_clip(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_push_clip_round")) {
        ui_push_clip_round(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_pop_clip")) {
        ui_pop_clip(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_clipped")) {
        ns_bool result = ui_rect_clipped(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_create")) {
        i32 result = ui_rect_batch_create(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_destroy")) {
        ui_rect_batch_destroy(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_begin")) {
        ui_rect_batch_begin(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_add")) {
        ui_rect_batch_add(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_end")) {
        ns_bool result = ui_rect_batch_end(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_draw")) {
        ui_rect_batch_draw(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_rect_batch_draw_at")) {
        ui_rect_batch_draw_at(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_draw_text")) {
        ui_draw_text(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_embedded_arg_str(vm, 3), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 5)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 6)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_draw_text_wrapped")) {
        f64 result = ui_draw_text_wrapped(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_embedded_arg_str(vm, 4), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 6)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 7)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_text_line_height")) {
        f64 result = ui_text_line_height(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_text_v_center_y")) {
        f64 result = ui_text_v_center_y(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 4)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_measure_text")) {
        ui_text_size *result = ui_measure_text(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)));
        ns_embedded_return_struct(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_text_width")) {
        f64 result = ui_text_width(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_mono_char_width")) {
        f64 result = ui_mono_char_width(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_create")) {
        void *result = ui_widgets_create(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_destroy")) {
        ui_widgets_destroy(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_set_light")) {
        ui_widgets_set_light(ns_embedded_arg_pointer(vm, 0), ns_eval_bool(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_begin_frame")) {
        ui_widgets_begin_frame(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_pointer(vm, 1), ns_embedded_arg_pointer(vm, 2));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_begin_view")) {
        ui_widgets_begin_view(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_pointer(vm, 1), ns_embedded_arg_pointer(vm, 2), ns_eval_bool(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_end_frame")) {
        ui_widgets_end_frame(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_button")) {
        ns_bool result = ui_button(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_embedded_arg_str(vm, 6), ns_eval_bool(vm, ns_embedded_arg(vm, 7)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_slider")) {
        f64 result = ui_slider(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 6)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 7)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 8)), ns_eval_bool(vm, ns_embedded_arg(vm, 9)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_slider_rect")) {
        f64 result = ui_slider_rect(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), (ui_rect *)ns_embedded_arg_pointer(vm, 2), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_slider_id")) {
        f64 result = ui_slider_id(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), (ui_rect *)ns_embedded_arg_pointer(vm, 2), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_hit_region")) {
        ui_hit *result = ui_hit_region(ns_embedded_arg_pointer(vm, 0), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)));
        ns_embedded_return_struct(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_is_escape_pressed")) {
        ns_bool result = ui_is_escape_pressed(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_is_enter_pressed")) {
        ns_bool result = ui_is_enter_pressed(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_is_mouse_down")) {
        ns_bool result = ui_is_mouse_down(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_is_mouse_pressed")) {
        ns_bool result = ui_is_mouse_pressed(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_has_keyboard_focus")) {
        ns_bool result = ui_has_keyboard_focus(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_mouse_x")) {
        f64 result = ui_widgets_mouse_x(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_widgets_mouse_y")) {
        f64 result = ui_widgets_mouse_y(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_color_picker")) {
        ui_color_rgba *result = ui_color_picker(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 4)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 5)), (ui_color_rgba *)ns_embedded_arg_pointer(vm, 6));
        ns_embedded_return_struct(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_color_picker_rect")) {
        ui_color_rgba *result = ui_color_picker_rect(ns_embedded_arg_pointer(vm, 0), ns_embedded_arg_str(vm, 1), (ui_rect *)ns_embedded_arg_pointer(vm, 2), (ui_color_rgba *)ns_embedded_arg_pointer(vm, 3));
        ns_embedded_return_struct(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_color_picker_id")) {
        ui_color_rgba *result = ui_color_picker_id(ns_embedded_arg_pointer(vm, 0), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), (ui_rect *)ns_embedded_arg_pointer(vm, 2), (ui_color_rgba *)ns_embedded_arg_pointer(vm, 3));
        ns_embedded_return_struct(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_pack_color")) {
        u32 result = ui_pack_color(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "ui") && ns_str_equals_STR(fn->name, "ui_pack_rgba_floats")) {
        u32 result = ui_pack_rgba_floats(ns_eval_number_f64(vm, ns_embedded_arg(vm, 0)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 2)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 3)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_lock_create")) {
        void *result = os_lock_create();
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_lock_acquire")) {
        ns_bool result = os_lock_acquire(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_lock_try_acquire")) {
        ns_bool result = os_lock_try_acquire(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_lock_release")) {
        ns_bool result = os_lock_release(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_lock_destroy")) {
        os_lock_destroy(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_create")) {
        void *result = os_semaphore_create(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_create_bounded")) {
        void *result = os_semaphore_create_bounded(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_wait")) {
        ns_bool result = os_semaphore_wait(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_try_wait")) {
        ns_bool result = os_semaphore_try_wait(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_signal")) {
        ns_bool result = os_semaphore_signal(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_semaphore_destroy")) {
        os_semaphore_destroy(ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_time")) {
        f64 result = os_time();
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_time_ms")) {
        u64 result = os_time_ms();
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_time_us")) {
        u64 result = os_time_us();
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_time_ns")) {
        u64 result = os_time_ns();
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_date_now")) {
        void *result = os_date_now();
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_time_string")) {
        const char *result = os_time_string();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_date_string")) {
        const char *result = os_date_string();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_locale_date_string")) {
        const char *result = os_locale_date_string();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_locale_date_time_string")) {
        const char *result = os_locale_date_time_string();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_vibrate")) {
        os_vibrate(ns_eval_number_f64(vm, ns_embedded_arg(vm, 0)), ns_eval_number_f64(vm, ns_embedded_arg(vm, 1)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_file_size")) {
        i64 result = os_file_size(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_read_file")) {
        const char *result = os_read_file(ns_embedded_arg_str(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_read_file_part")) {
        const char *result = os_read_file_part(ns_embedded_arg_str(vm, 0), ns_eval_number_i64(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i64(vm, ns_embedded_arg(vm, 2)));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_write_file_atomic")) {
        i32 result = os_write_file_atomic(ns_embedded_arg_str(vm, 0), ns_embedded_arg_str(vm, 1));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_app_data_dir")) {
        const char *result = os_app_data_dir(ns_embedded_arg_str(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_dir_scan")) {
        i32 result = os_dir_scan(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_entry_name")) {
        const char *result = os_entry_name(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_entry_path")) {
        const char *result = os_entry_path(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_entry_depth")) {
        i32 result = os_entry_depth(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_entry_parent")) {
        i32 result = os_entry_parent(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_entry_is_dir")) {
        i32 result = os_entry_is_dir(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_watch_start")) {
        i32 result = os_watch_start(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_watch_poll")) {
        i32 result = os_watch_poll();
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_watch_stop")) {
        os_watch_stop();
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_open_file_dialog")) {
        const char *result = os_open_file_dialog(ns_embedded_arg_str(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_save_file_dialog")) {
        const char *result = os_save_file_dialog(ns_embedded_arg_str(vm, 0), ns_embedded_arg_str(vm, 1));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_open_folder_dialog")) {
        const char *result = os_open_folder_dialog(ns_embedded_arg_str(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_cwd")) {
        const char *result = os_cwd();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_env")) {
        const char *result = os_env(ns_embedded_arg_str(vm, 0));
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_make_dirs")) {
        i32 result = os_make_dirs(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "os") && ns_str_equals_STR(fn->name, "os_launch_ns_project")) {
        i32 result = os_launch_ns_project(ns_embedded_arg_str(vm, 0), ns_embedded_arg_str(vm, 1));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_request_device")) {
        ns_bool result = gpu_request_device(ns_embedded_arg_pointer(vm, 0));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_destroy_device")) {
        gpu_destroy_device();
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_shader_target")) {
        const char *result = gpu_shader_target();
        call->ret.t = ns_type_str;
        call->ret.o = ns_vm_push_string(vm, result ? ns_str_cstr((char *)result) : ns_str_null);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_dispatch_compute_source")) {
        ns_bool result = gpu_dispatch_compute_source(ns_embedded_arg_str(vm, 0), ns_embedded_arg_str(vm, 1), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 4)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_create_buffer")) {
        u32 result = gpu_create_buffer(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_update_buffer")) {
        gpu_update_buffer(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)), ns_embedded_arg_pointer(vm, 1), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_create_shader_source")) {
        u32 result = gpu_create_shader_source(ns_embedded_arg_str(vm, 0), ns_embedded_arg_str(vm, 1), ns_embedded_arg_str(vm, 2), ns_embedded_arg_str(vm, 3));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_create_pipeline_layout")) {
        u32 result = gpu_create_pipeline_layout(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_embedded_arg_pointer(vm, 2), ns_embedded_arg_pointer(vm, 3), ns_embedded_arg_pointer(vm, 4), ns_eval_number_i32(vm, ns_embedded_arg(vm, 5)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 6)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 7)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_create_mesh_1")) {
        u32 result = gpu_create_mesh_1(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_u32(vm, ns_embedded_arg(vm, 1)));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_destroy_buffer_id")) {
        gpu_destroy_buffer_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_destroy_shader_id")) {
        gpu_destroy_shader_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_destroy_pipeline_id")) {
        gpu_destroy_pipeline_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_destroy_mesh_id")) {
        gpu_destroy_mesh_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_begin_render_pass_id")) {
        gpu_begin_render_pass_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_pipeline_id")) {
        gpu_set_pipeline_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_mesh_id")) {
        gpu_set_mesh_id(ns_eval_number_u32(vm, ns_embedded_arg(vm, 0)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_begin_render_pass")) {
        gpu_begin_render_pass(*(gpu_render_pass *)ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_viewport")) {
        gpu_set_viewport(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_scissor")) {
        gpu_set_scissor(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 3)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_pipeline")) {
        gpu_set_pipeline(*(gpu_pipeline *)ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_binding")) {
        gpu_set_binding(*(gpu_binding *)ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_set_mesh")) {
        gpu_set_mesh(*(gpu_mesh *)ns_embedded_arg_pointer(vm, 0));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_draw")) {
        gpu_draw(ns_eval_number_i32(vm, ns_embedded_arg(vm, 0)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 1)), ns_eval_number_i32(vm, ns_embedded_arg(vm, 2)));
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_end_pass")) {
        gpu_end_pass();
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "gpu") && ns_str_equals_STR(fn->name, "gpu_commit")) {
        gpu_commit();
        call->ret = ns_nil;
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "io") && ns_str_equals_STR(fn->name, "io_load_image")) {
        void *result = io_load_image(ns_embedded_arg_str(vm, 0));
        ns_embedded_return_pointer(vm, result);
        return ns_return_ok(bool, true);
    }
    else if (ns_str_equals_STR(fn->lib, "io") && ns_str_equals_STR(fn->name, "io_save_image")) {
        ns_bool result = io_save_image(ns_embedded_arg_str(vm, 0), ns_embedded_arg_pointer(vm, 1));
        ns_embedded_return_scalar(vm, &result, sizeof(result));
        return ns_return_ok(bool, true);
    }
    return ns_return_error(bool, ns_code_loc_nil, NS_ERR_EVAL, "embedded native function is not forwarded");
}
#endif
