#include "ns_code_gen.h"
#include "ns_parse.h"
#include "ns_type.h"

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct ns_code_gen_ctx_t {
    ns_str path;
    FILE *fd;
    ns_parse_context_t *ctx;
} ns_code_gen_ctx_t;

bool ns_code_gen_arm64(ns_parse_context_t *ctx) {
    ns_str asm_path = ns_str_cstr("bin/asm.s");
    printf("generate arm64 assemble file: %s\n", asm_path.data);

    FILE *fd = fopen(asm_path.data, "w");
    if (!fd) {
        fprintf(stderr, "failed to open file %s\n", asm_path.data);
        return false;
    }

    fprintf(fd, "# generated by ns\n# @copyright liamlangli\n");

    ns_code_gen_ctx_t code_gen_ctx = {.path=asm_path, .fd=fd, .ctx=ctx};
    int i = 0;
    int l = ctx->section_count;

    while (i < l) {
        int s = ctx->sections[i++];
        ns_ast_t n = ctx->nodes[s];

        switch (n.type) {
            case NS_AST_FN_DEF:
                break;
            default:
                break;
        }
    }

    fclose(fd);
    return true;
}